# Taskfile.yml - Build automation for plat-rclone
# Use with: xplat task <name> or task <name>
version: '3'

vars:
  DATASTAR_VERSION: v1.0.0-RC.7
  GOUP_VERSION: v2.0.0
  BINARY: plat-rclone

tasks:
  # === Debug ===

  debug:
    desc: Show environment info (for CI debugging)
    cmds:
      - echo "OS={{OS}} ARCH={{ARCH}}"
      - echo "HOME={{.HOME}}"
      - echo "PWD=$(pwd)"
      - echo "--- .bin/ ---"
      - ls -la .bin/ 2>/dev/null || echo ".bin/ not found"
      - echo "--- .dist/ ---"
      - ls -la .dist/ 2>/dev/null || echo ".dist/ not found"
      - echo "--- PATH ---"
      - echo "$PATH" | tr ':' '\n' | head -10

  # === Development ===

  default:
    desc: Show available tasks
    cmds:
      - task --list

  dev:
    desc: Run dev server (HTTP mode - needs rclone rcd)
    deps: [templ]
    cmds:
      - go run ./cmd/plat-rclone serve

  dev-embedded:
    desc: Run dev server (embedded rclone, local backend)
    deps: [templ]
    cmds:
      - go run ./cmd/plat-rclone serve -embedded

  dev-embedded-full:
    desc: Run dev server (embedded rclone, all backends)
    deps: [templ]
    cmds:
      - go run -tags=rclone_full ./cmd/plat-rclone serve -embedded

  # === Build ===

  templ:
    desc: Generate templ files
    cmds:
      - templ generate
    sources:
      - templates/*.templ
    generates:
      - templates/*_templ.go

  build:
    desc: Build web server binary
    deps: [templ]
    cmds:
      - go build -o .bin/{{.BINARY}}-web ./cmd/plat-rclone

  build-full:
    desc: Build with all rclone backends
    deps: [templ]
    cmds:
      - go build -tags=rclone_full -o .bin/{{.BINARY}}-web-full ./cmd/plat-rclone

  # === Native Apps (via goup-util) ===

  macos:
    desc: Build macOS .app bundle
    deps: [templ]
    cmds:
      - goup-util build macos .

  ios:
    desc: Build iOS .app
    deps: [templ]
    cmds:
      - goup-util build ios .

  android:
    desc: Build Android .apk
    deps: [templ]
    cmds:
      - goup-util build android .

  windows:
    desc: Build Windows .exe
    deps: [templ]
    cmds:
      - goup-util build windows .

  all:
    desc: Build all platforms
    deps: [templ]
    cmds:
      - task: macos
      - task: ios
      - task: android
      - task: windows

  # === Run ===

  run-macos:
    desc: Run macOS app
    deps: [macos]
    cmds:
      - open .bin/*.app

  run-web:
    desc: Run web server
    deps: [build]
    cmds:
      - .bin/{{.BINARY}}-web serve

  ios-sim:
    desc: Install and run on iOS simulator
    deps: [ios]
    cmds:
      - xcrun simctl install booted .bin/*.app
      - xcrun simctl launch booted com.github.plat_rclone

  # === Release ===

  release:
    desc: Build release for current platform
    deps: [templ]
    cmds:
      - xplat os mkdir -p .dist
      - task: build
      - task: build-full
      - task: release:package

  release:package:
    desc: Package builds for release
    internal: true
    cmds:
      - goup-util package {{OS}} .

  release:macos:
    desc: Build macOS release (app bundle + web binaries)
    deps: [templ]
    cmds:
      - mkdir -p .dist
      - task: macos
      - task: build
      - task: build-full
      # Zip app bundle - goup-util outputs to .bin/macos/ on CI, .bin/ locally
      - |
        if [ -d .bin/macos ]; then
          cd .bin/macos && zip -r ../../.dist/{{.BINARY}}-macos.zip *.app
        else
          cd .bin && zip -r ../.dist/{{.BINARY}}-macos.zip *.app
        fi
      - cp .bin/{{.BINARY}}-web .dist/{{.BINARY}}-macos-amd64
      - cp .bin/{{.BINARY}}-web-full .dist/{{.BINARY}}-full-macos-amd64

  release:linux:
    desc: Build Linux release (web binaries only, no GUI)
    deps: [templ]
    cmds:
      - mkdir -p .dist
      - task: build
      - task: build-full
      - cp .bin/{{.BINARY}}-web .dist/{{.BINARY}}-linux-amd64
      - cp .bin/{{.BINARY}}-web-full .dist/{{.BINARY}}-full-linux-amd64

  release:windows:
    desc: Build Windows release (web binaries only)
    deps: [templ]
    cmds:
      - mkdir -p .dist
      - go build -o .dist/{{.BINARY}}-windows-amd64.exe ./cmd/plat-rclone
      - go build -tags=rclone_full -o .dist/{{.BINARY}}-full-windows-amd64.exe ./cmd/plat-rclone

  # === Utils ===

  download:
    desc: Download rclone binary
    cmds:
      - go run ./cmd/plat-rclone download .bin

  datastar:
    desc: Download Datastar JS bundles
    cmds:
      - mkdir -p static/js
      - 'curl -sL "https://raw.githubusercontent.com/starfederation/datastar/{{.DATASTAR_VERSION}}/bundles/datastar.js" -o static/js/datastar.js'
      - 'curl -sL "https://raw.githubusercontent.com/starfederation/datastar/{{.DATASTAR_VERSION}}/bundles/datastar.js.map" -o static/js/datastar.js.map'
      - echo "Downloaded Datastar {{.DATASTAR_VERSION}}"

  icons:
    desc: Generate app icons from icon-source.png
    cmds:
      - goup-util icons .

  screenshot:
    desc: Take iOS simulator screenshot
    cmds:
      - xcrun simctl io booted screenshot docs/ios-screenshot.png
      - echo "Saved docs/ios-screenshot.png"

  # === Setup ===

  setup:
    desc: Install all required tools (idempotent, cross-platform)
    deps: [setup:templ, setup:goup, setup:gogio]

  setup:gogio:
    desc: Install gogio (Gio build tool)
    internal: true
    status:
      - xplat os which gogio
    cmds:
      - go install gioui.org/cmd/gogio@latest

  setup:templ:
    desc: Install templ
    internal: true
    status:
      - xplat os which templ
    cmds:
      - go install github.com/a-h/templ/cmd/templ@latest

  setup:goup:
    desc: Install goup-util
    internal: true
    vars:
      EXT: '{{if eq OS "windows"}}.exe{{end}}'
      BIN: '{{if eq OS "windows"}}{{.USERPROFILE}}/go/bin{{else}}{{.HOME}}/.local/bin{{end}}'
    status:
      - xplat os which goup-util
    cmds:
      - xplat os mkdir -p {{.BIN}}
      - xplat os fetch -o {{.BIN}} "https://github.com/joeblew999/goup-util/releases/download/{{.GOUP_VERSION}}/goup-util-{{OS}}-{{ARCH}}{{.EXT}}"
      - xplat os mv {{.BIN}}/goup-util-{{OS}}-{{ARCH}}{{.EXT}} {{.BIN}}/goup-util{{.EXT}}
      - '{{if ne OS "windows"}}chmod +x {{.BIN}}/goup-util{{end}}'

  # === Quality ===

  test:
    desc: Run tests
    cmds:
      - go test ./cmd/... ./pkg/... ./templates/...

  fmt:
    desc: Format code
    cmds:
      - go fmt ./...
      - templ fmt templates/

  lint:
    desc: Run linter
    cmds:
      - golangci-lint run ./...
    ignore_error: true

  clean:
    desc: Remove build outputs
    cmds:
      - rm -rf .bin .build .releases
      - echo "Cleaned"
